featurex/extractors/image.py

Implemented extractors:
+ Brightness
+ Sharpness
+ Metamind extractors
+ General extractor
+ [Indoor/outdoor] (https://www.metamind.io/classifiers/25463)
+ [Facial expressions] (https://www.metamind.io/classifiers/30198)

Metamind extractors and other simple extractors

---

featurex/tests/test_datasets.py

Add test for text dictionaries.

---

featurex/extractors/image.py
featurex/tests/test_extractors.py
optional-dependencies.txt

added SaliencyExtractor and associated tests; changed 'img' to 'stim' in extractors/image.py

Added SaliencyExtractor

---

.travis.yml
optional-dependencies.txt

Will help improve test coverage

Encrypted API keys added to .travis.yml

---

featurex/stimuli/video.py
featurex/tests/test_stims.py

Added unit tests for existing DerivedVideoStim class
Added functionality to filter frames using method outlined in #31 
Some refactoring

Video stimuli keyframes

---

featurex/converters/api.py
featurex/converters/audio.py
featurex/extractors/api.py
featurex/tests/test_converters.py
featurex/tests/test_extractors.py

-Converted the Wit API extractor to an AudioToText converter
-Wrote an AudioToText converter using the Google Speech API
-Corresponding unit tests updated

Speech recognition converters

---

featurex/extractors/image.py
featurex/tests/test_extractors.py

This fixes all ImageExtractors and their tests as per #56. Still leaves the API, video, google, and text Extractors broken.

fixed all ImageExtractors per #56

---

featurex/converters/api.py
featurex/stimuli/text.py
featurex/tests/test_converters.py

IBM speech API

---

featurex/diagnostics/outliers.py
featurex/extractors/api.py
featurex/extractors/audio.py
featurex/extractors/google.py
featurex/extractors/image.py
featurex/extractors/text.py
featurex/extractors/video.py
featurex/stimuli/text.py
featurex/tests/test_core.py
featurex/tests/test_diagnostics.py
featurex/tests/test_extractors.py
featurex/tests/test_google_extractors.py
featurex/tests/test_graph.py
featurex/tests/test_io.py

Updated api, google, text, and video extractors to use the new `ExtractorResult` format. Also made some fixes to get tests passing (included commenting out tests for old extractor format). Various other miscellany.
~~TODO (separate task/PR): remove all old extractor code~~ Addressed in #66

Updated extractors

---

featurex/converters/api.py
featurex/extractors/__init__.py
featurex/google.py
featurex/graph.py
featurex/stimuli/__init__.py
featurex/stimuli/audio.py
featurex/stimuli/image.py
featurex/stimuli/text.py
featurex/stimuli/video.py
featurex/tests/test_converters.py
featurex/tests/test_extractors.py
featurex/tests/test_graph.py
featurex/tests/utils.py
featurex/transformers.py

Implements ability to process stimuli in batch, along with various other fixes and improvements.

Batch processing

---

featurex/converters/__init__.py
featurex/converters/api.py
featurex/tests/test_core.py
featurex/tests/test_extractors.py
featurex/transformers.py

An implementation of automatic stimuli conversion during validation of any transformation. Searches through available converters and uses one with the appropriate `_input_type` and `_output_type`, if one is found. Also added appropriate units tests.
Resolves #48

Implicit stimuli conversion

---

featurex/stimuli/video.py

Addresses issue raised by @qmac in #76.

fix data attribute in VideoFrameStim init

---

pliers/config.py
pliers/converters/base.py
pliers/converters/video.py
pliers/extractors/base.py
pliers/graph.py
pliers/stimuli/base.py
pliers/transformers.py
pliers/utils.py
requirements.txt

Adds a progress bar when iterating lists of `Stim`s.

Progress bar

---

pliers/converters/api.py

Updated Google and IBM API speech-to-text processing

Minor fixes

---

.travis.yml
pliers/datasets/dictionaries.json
pliers/extractors/audio.py
pliers/stimuli/base.py
pliers/tests/test_utils.py
pliers/transformers.py

Minor fixes and improvements; nothing to write home about.

Minor improvements

---

pliers/converters/api.py
pliers/tests/test_converters.py

IBM transcription will now result in `ComplexTextStim`s with `TextStim` elements that are either words or phrases (user provided argument to the converter). Previously, it partitioned word-by-word only.

Added resolution to IBM transcription

---

.travis.yml
pliers/stimuli/base.py
pliers/tests/test_converters.py
requirements.txt

Fixes a bunch of issues in the travis config that were preventing the tests from passing. Also tweaks a couple of lines in the latest PRs that broke on Python 3.

Fix travis

---

pliers/graph.py
pliers/tests/test_graph.py

Should've tested parameter handling more.

Fixed param handling, more tests

---

pliers/export.py
pliers/tests/test_io.py

Small fix to `to_long_format` in `export.py`

Updated long format conversion

---

pliers/extractors/api.py

Minor Indico exception fix

---

pliers/extractors/base.py
pliers/graph.py
pliers/tests/test_extractors.py
pliers/tests/test_graph.py

- Keeping durations in graph results
- Including original `source_file` in graph results
- Allowing users to name nodes and transformers within a graph

Various fixes/slight enhancements

---

pliers/stimuli/base.py
pliers/tests/test_io.py

Loadstims appropriate error handling

---

pliers/stimuli/audio.py
pliers/stimuli/base.py
pliers/stimuli/image.py
pliers/stimuli/text.py
pliers/stimuli/video.py
pliers/tests/test_stims.py

Resolves #128 
Moved the existing code for `get_filename` methods to create a `save` method for all stims. Also refactored `get_filename` methods.

.save method for stims

---

pliers/converters/api.py

Should've caught this awhile ago, but one of the google tests was failing

Fix for Google speech-to-text

---

.travis.yml
examples/Scikit-Learn Integration.ipynb
optional-dependencies.txt
pliers/extractors/__init__.py
pliers/graph.py
pliers/scikit.py
pliers/sklearn.py
pliers/tests/test_scikit.py

Added code for wrapping `Extractor` or `Graph` objects as scikit-learn `Transformer`s.
Includes:
-Implementation
-Tests
-Example notebook illustrating basic usage within a sklearn `Pipeline` in `examples/`
Resolves #139

Sklearn integration

---

.travis.yml
pliers/converters/google.py
pliers/extractors/api.py
pliers/extractors/base.py
pliers/extractors/google.py
pliers/google.py
pliers/stimuli/text.py
pliers/tests/test_extractors.py
pliers/tests/test_google_extractors.py
pliers/tests/test_transformers.py
pliers/tests/test_utils.py
pliers/tests/utils.py
pliers/transformers.py
pliers/utils.py
requirements.txt

Still a WIP, need to sweep over other potential batch transformers.
Resolves #72. Added core logic in `transformers.py` to perform batch transformations within pliers.

Batch transformers

---

setup.py

Changed setup.py to accept numpy 1.12+

---

pliers/extractors/api.py
pliers/tests/extractors/test_api_extractors.py

Clarifai API extractor now uses api_key rather than ID and secret

---

README.md

Just a minor update to the readme

README - Clarifai API key

---

optional-dependencies.txt

OpenCV is opencv-python on pypi now

optional reqs - opencv

---

pliers/transformers.py

Resolves #206. Increments progress after each batch.

Progress bar wrapper for batch transformation

---

pliers/extractors/text.py
pliers/filters/__init__.py
pliers/filters/text.py
pliers/tests/extractors/test_text_extractors.py
pliers/tests/filters/test_text_filters.py

Resolves #215 
Added utility text filter for lower casing
Fixed ordering in `TokenizingFilter`

Minor text transformers updates

---

pliers/tests/test_transformers.py
pliers/tests/utils.py
pliers/transformers/base.py

Added test for caching as well.
Resolves #284

Fix for caching on stim paths

---

pliers/extractors/api/google.py

Fix missing RGB

---

docs/quickstart.rst

I found that I needed these to make the Quick Start demo work.

Add os.path and pliers.tests.utils imports

---

pliers/stimuli/audio.py

Set `unknown` fps to 44100

---

pliers/extractors/__init__.py
pliers/extractors/audio.py
pliers/tests/extractors/test_audio_extractors.py

Commented  code contains changes which are in-progress and not complete.

Adding remaining features for librosa.

---

requirements.txt

Bump imageio verson to accept pilmode

---

pliers/extractors/api/google.py

Add thresholds to GoogleVideoIntellgienceAPI

---

pliers/filters/__init__.py
pliers/filters/audio.py
pliers/tests/filters/test_audio_filters.py

Add `AudioResamplingFilter` based on `librosa.core.resample` as suggested in #370

Audio resampling filter

---

pliers/converters/misc.py
pliers/extractors/audio.py
pliers/extractors/misc.py
pliers/extractors/text.py

fixing indexing issue with BertLMExtractor onset/duration.

fix bertLM onset/duration

---

optional-dependencies.txt
pliers/extractors/audio.py

Remove soundfile as dependency 

---

.travis.yml
optional-dependencies.txt
pliers/support/setup_yamnet.py
pliers/tests/converters/test_image_converters.py
pliers/tests/extractors/test_audio_extractors.py
pliers/tests/test_graph.py
pliers/tests/utils.py

closes #416 
closes #417 
closes #419
This pull request makes versions for pytesseract, yamnet, and librosa more restrictive.

[FIX] tests

---

pliers/extractors/audio.py

updates links to librosa features in extractor docstrings.
Closes #425.

Fix librosa links

---

pliers/tests/test_utils.py
pliers/utils/base.py

- Minor bug in #426 such that upsampling failed, due to a rounding error. 
- The requested interpolated values were also subject to a rounding error, so I fixed them to the new onsets * upsampled sr, to ensure they were exactly the same. 
- Fixed and added upsampling test

FIX: Fix resample upsampling and add upsampling test case

---

.github/workflows/publish-to-test-pypi.yml

Automatically release to pypi if a tagged release is pushed

Add GH Release workflow

---

.github/workflows/build-docs.yml
docs/reference.rst

Add gh-action to update docs when merged to master. Added a test change to see if this works.

Update docs with gh actions

---

.github/workflows/build-docs.yml
.github/workflows/pull_request.yml

This attempts to build the docs in the PR so that you can test that they successfully build.

Add PR docs gh-action check

---

.github/workflows/build-docs.yml

- Need to clone *this* repo to make correct push

FIX: Clone correct repo for doc update

---

pliers/tests/extractors/test_audio_extractors.py
pliers/tests/test_io.py
pliers/tests/test_stims.py

Tests began to fail due to slight changes in values, and online stimuli that had to be replaced.

FIX: Tests

---

README.rst

Small fix to the correct links.

Update links from Naturalistic Data course

---

.github/workflows/python-package.yml
optional-dependencies.txt
pliers/tests/test_io.py
pliers/tests/test_stims.py

ffmpeg failing on remote files in CI

CI/TESTING: Updated ffmpeg, expand to Python 3.10
