featurex/core.py, featurex/tests/test_core.py
Instead of implementing the dummy coding at the export step, it's implemented in the Timeline (see Timeline.dummy_code()).
=> Adds ability to dummy-code Timeline; closes #9

featurex/converters/api.py, featurex/converters/google.py, featurex/converters/image.py, featurex/converters/video.py, featurex/extractors/google.py, featurex/extractors/image.py, featurex/google.py, featurex/stimuli/video.py, featurex/tests/test_converters.py, featurex/tests/test_extractors.py, featurex/tests/test_google_extractors.py, featurex/tests/test_stims.py
(1) Moved `DerivedVideoStim` `filter` functionality to a `FrameSamplingConverter`
(2) Moved `TesseractAPIExtractor` to a `TesseractAPIConverter` which inherits `ImageToTextConverter`
(3) Moved `GoogleVisionAPITextExtractor` to `GoogleVisionAPITextConverter` which also inherits `ImageToTextConverter` and required (4)
(4) Refactored core GoogleAPI interaction (working with credentials, executing requests, building requests for the Vision API) to a package-wide `GoogleAPITransformer` class, which can be subclassed by both `Extractors` and `Converters`.
=> Moving extractors to converters

featurex/converters/__init__.py, featurex/converters/api.py, featurex/stimuli/__init__.py, featurex/stimuli/text.py, featurex/stimuli/video.py, featurex/tests/test_converters.py, featurex/tests/test_graph.py
When a stimulus is converted into another, tack on source information to the new stimulus.
Implemented with this in mind:
-`name` property holds what the stimulus should be called in an `ExtractorResult`
-`id` property holds a unique identifier for a stimulus, typically for those belonging to a `CollectionStimMixin`
There was some overlap with #80 but I don't think there will be any merge conflicts.
=> Propagate stimulus name during conversion

featurex/converters/__init__.py, featurex/converters/api.py, featurex/converters/video.py
Somewhat addresses #91 but it currently fails.
The problem with memoizing via joblib: we can’t pickle conversions of `VideoStim`s because pickling requires serializing `VideoClip`s which requires serializing `AudioClip`s. This doesn't work since `AudioClip`s have the property `make_frame` which is a lambda function. Unfortunately `pickle` does not like lambdas. This may be solved by using `dill`, but joblib seems to have stalled at implementing this (see https://github.com/joblib/joblib/pull/240).
There may be workarounds for this, or we can explore other caching libraries.
=> Caching conversions

featurex/converters/__init__.py, featurex/stimuli/audio.py, featurex/tests/test_converters.py
Minor bug fix that prevented proper caching, and a very basic and rather crummy timing-based test that should probably be improved, as it could fail in unusual environments.
=> fixes caching bug and adds a basic test; closes #91

pliers/converters/__init__.py, pliers/converters/multistep.py, pliers/converters/video.py, pliers/tests/test_converters.py, pliers/tests/test_extractors.py, pliers/transformers.py
This re-applies all the changes in #96 (sorry @qmac--I forgot about this PR until after I merged the name change PR, and it was much easier to manually apply your edits than to resolve the million merge conflicts it introduced), and some minor improvements (creates a new `multistep` module under `converters`, and allows passing of both `Converter`s and `Stim`s as `steps`).
=> Converter improvements

examples/Graph.ipynb, examples/VisionAPIs.ipynb, pliers/converters/base.py, pliers/extractors/base.py, pliers/filters/base.py, pliers/tests/test_converters.py, pliers/tests/test_extractors.py, pliers/tests/test_google_extractors.py, pliers/tests/test_io.py, pliers/tests/test_stims.py, pliers/tests/test_transformers.py
On reflection, I decided it's a bad idea to have separate convert(), extract() and filter() methods that are all aliases for transform() and have no purpose other than signaling what kind of `Transformer` we're dealing with. From now on, all transformation calls should be made strictly with `.transform()`.
=> removed convert() and extract(); only transform() remains

pliers/stimuli/base.py, pliers/tests/test_transformers.py, pliers/transformers.py
This is a small but useful tweak that allows passing of filenames directly to `Transformers`. I.e., in addition to this:
```python
img = ImageStim('my_image.jpg')
ext = MyExtractor()
result = ext.extract(img)
```
...a user can now do this:
```python
ext = MyExtractor()
result = ext.extract('my_image.jpg')
```
This leverages the `stimulus.load_stims` function, which already does intelligent loading of `Stim`s from filename strings based on the MIME type (via python-magic).
=> enable passing strings to Transformers

pliers/config.py, pliers/converters/__init__.py, pliers/converters/api.py, pliers/converters/audio.py, pliers/converters/base.py, pliers/converters/multistep.py, pliers/extractors/__init__.py, pliers/extractors/base.py, pliers/extractors/text.py, pliers/google.py, pliers/stimuli/base.py, pliers/stimuli/video.py, pliers/tests/test_converters.py, pliers/tests/test_extractors.py, pliers/tests/test_graph.py, pliers/transformers.py, pliers/utils.py
This PR contains mostly minor fixes and improvements. The only (possibly) notable changes include:
* A new `EnvironmentKeyMixin` class that should be mixed into any `Transformer` that needs to use environment variables (mostly API keys for web services). This makes it easy to check whether the transformer is `.available` (i.e., all required environment keys are present).
* Default `Converter`s for any given pair of `Stim` types can now be set in the `config` module.
* Naming conventions have changed (yet again). `Stim`s now do *not* include any historical info in the name (e.g., video frames do not include the name of the source video). The reason for this is that `ExtractorResult`-derived DataFrames now return a bunch of info about stimulus class, history, etc., so using the `name` …
=> Various fixes

pliers/datasets/text.py
Well I didn't mean to go down this path, but the downsampling of video was not going well on my measly laptop so I tried to do it on deepdream. 
For some reason, in windows when a file is in utf-8 encoding, that must be stated in `open`, and not in `json.load`. 
However, only python3 has different encodings in the `open` function. Turns out that you can make it python 2 and 3 compatible using open from the io library. Test seem to run well (aside from missing corpus ones for me).
=> Using io to open for encoding utf-8

.travis.yml, optional-dependencies.txt, pliers/extractors/__init__.py, pliers/extractors/models.py, pliers/stimuli/audio.py, pliers/tests/test_extractors.py
This PR adds a new `extractors.models` submodule that will house Extractors based on pre-trained DNN models. I've added a new `TensorFlowInceptionV3Extractor` that does image labeling based on the pre-trained Inception V3 model discussed in the [TF docs](https://www.tensorflow.org/tutorials/image_recognition/#usage_with_python_api). See test for example usage, which follows the standard `Extractor` pattern. The 200 MB pretrained model will be downloaded the first time the extractor is run, if it' s not found, and no additional code is required.
=> added new TensorFlowInceptionV3Extractor based on TF example

pliers/config.py, pliers/converters/google.py, pliers/extractors/api.py, pliers/extractors/base.py, pliers/graph.py, pliers/stimuli/base.py, pliers/stimuli/compound.py, pliers/stimuli/text.py, pliers/tests/test_extractors.py, pliers/tests/test_graph.py, pliers/transformers.py
This PR closes several issues and adds some other improvements:
* Every `Transformer` class now has an `_optional_input_types` property (which can almost always be ignored and left to use the empty value in the base `Transformer` class) that specifies which input `Stim` classes are acceptable but not required. This closes #105 and allows creation of `Transformer` classes that can handle one of several different `Stim` inputs (e.g., the `IndicoAPIExtractor` can batch-submit documents, so it can now handle both `ComplexTextStim` and `TextStim` inputs, behaving more efficiently in the former case).
* In `graph.py`, the order of the arguments to `_parse_node_args` has been changed from `(Transformer, name, children)` to `(Transformer, children, name)`, because the `name` attribute is almost …
=> General improvements and fixes

setup.py
In #113 package data was not being copied over during install in regular installs. 
Looks like the issue was `package_data` in `setup.py` was fetching pliers/data but dictionaries.json is in pliers/datasets.
This fixed it on osx, windows and linux for me.
=> Added datasets to package_data

.travis.yml, optional-dependencies.txt, pliers/extractors/audio.py, pliers/graph.py, pliers/stimuli/base.py, pliers/tests/test_graph.py
Adds basic support for graph plotting. When calling `.draw()` on a `Graph` instance that's already been executed at least once (i.e., by calling `.run()`), a graph diagram of all transformations is generated via pygraphviz. Here's what it looks like for the `Graph` constructed in one of the tests:
We probably want to tweak this some more; e.g., it would be nice to differentiate between explicit transformations and implicit conversions, treat all of the different ExtractorResult nodes as a single node, etc... But for now, I think this is already quite useful.
=> Graph plotting

pliers/extractors/__init__.py, pliers/extractors/api.py, pliers/tests/test_extractors.py
This is work in progress to address #144 
I've mostly focused on creating a base Indico class, and specialized Image and Text classes. Tests are passing for text. But I wanted to open this issue to discuss the fact that for Text, you can now choose the unit of analysis (e.g. word, or phrase). Ideally, we want to abstract away that piece of logic, so that the scorer/annotator can do its job for all. I suppose for VideoStims you could potentially also choose what the unit of analysis is, but right now that is being done by the implicit conversion to ImageStim at some sampling rate. 
Sounds like @qmac implemented it the same way for TextStim so we should be set.
=> Indico image extractors

pliers/converters/api.py, pliers/extractors/api.py, pliers/extractors/models.py, pliers/google.py, pliers/stimuli/audio.py, pliers/stimuli/image.py, pliers/stimuli/video.py, pliers/tests/test_stims.py
Many transformers require a local file to work. Previously, we just created a temp file on the fly in the transformer logic. This PR moves the logic to a `get_filename` method in the stim classes, to prevent code reuse.
=> Moved temp file management to stim classes

.travis.yml
Using older version (0.2.2.13) of moviepy.
Based on the build logs, most likely something to deal with https://github.com/Zulko/moviepy/issues/518, which came up in the recent moviepy release.
=> Fix for Python3 travis build

pliers/converters/api.py, pliers/converters/video.py, pliers/extractors/audio.py, pliers/stimuli/text.py, pliers/stimuli/video.py, pliers/tests/test_converters.py, pliers/tests/test_extractors.py, pliers/tests/test_stims.py
In order to resolve #161 I just made sure each `stim` object always holds its absolute onset, propagated through conversion and extraction. I added several tests for this capability, but more might be necessary. This will require all future converters to make sure the absolute onset is used for resultant stimuli.
=> Making everything store absolute onsets

pliers/extractors/base.py, pliers/stimuli/base.py, pliers/tests/test_extractors.py, pliers/tests/test_graph.py, pliers/tests/utils.py
Resolves #172 . Additionally added test to make sure the error doesn't come up again.
No longer using stim id to hash, instead added the stim's history in the hash calculation. We *think* this captures true stim equality/uniqueness.
Modified the `DummyExtractor` in `utils.py` for tests to use proper `Extractor` convention, and prevent corresponding test failures.
=> Stimuli uniqueness

pliers/extractors/base.py, pliers/tests/test_extractors.py
Refactored the way extraction metadata gets added. Now a single `ExtractorResult` will can have that data when `to_df` is called (Resolves #164). Also made the metadata management in `merge_features` a bit more straightforward.
=> Extraction metadata management

pliers/extractors/api.py, pliers/extractors/models.py, pliers/filters/text.py, pliers/stimuli/audio.py, pliers/tests/test_extractors.py, pliers/tests/test_filters.py
- Went through and made sure all `_log_attributes` were correct
- Went through and made all appropriate `Transformers` inherit the `EnvironmentKeyMixin`
- Upgraded the `ClarifaiAPIExtractor` to use v2 of the API
- Adjusted `TensorFlowInceptionV3Extractor` to output in the same format as other object recognition extractors, i.e. using objects as columns instead of the `label_1` `score_1` format
- Fixed bug in stemming filter by removing the `WordNetLemmatizer` since it does not have a `.stem` method
=> Minor cleanup and improvements

.travis.yml, optional-dependencies.txt, pliers/stimuli/__init__.py, pliers/stimuli/api.py, pliers/tests/test_stims.py
Got a basic layout for twitter integration for pliers. `TweetStim`s inherit `CompoundStim` such that it can be comprised of text, images, and/or videos. 
Tweets can either by created via the `TweetStimFactory`, which handles the API authentication, or directly by passing a `Status` object from the `python-twitter` library to the `TweetStim` constructor.
Probably could further develop how we get tweets (firehose, other things outside of just status-by-status).
Resolves #131
=> Twitter Support

pliers/extractors/image.py, pliers/stimuli/image.py
To fix #184 we can force RGB when opening images. 
It might be useful to also add BW images to the test suite. Any free images we can use?
Maybe this one? https://en.wikipedia.org/wiki/File:Grayscale_8bits_palette_sample_image.png
Might be overkill though.
=> Force open images in RGB

pliers/extractors/text.py, pliers/tests/test_datasets.py, pliers/tests/test_extractors.py
The POS tag extractor now operates on `TextStim` units instead of `ComplexTextStim`s, which conforms better to the rest of the text transformers.
Also using GET requests in `test_datasets` because the HEAD requests were failing all of the sudden.
=> POS tag extractor fix

pliers/converters/api.py, pliers/converters/google.py, pliers/converters/image.py, pliers/converters/iterators.py, pliers/converters/video.py, pliers/extractors/api.py, pliers/extractors/audio.py, pliers/extractors/google.py, pliers/extractors/image.py, pliers/extractors/models.py, pliers/extractors/text.py, pliers/filters/image.py, pliers/filters/video.py, pliers/tests/test_transformers.py, pliers/transformers.py, pliers/utils.py
Resolves #191.
I was fairly conservative with which are "prime time", but those that are have `VERSION="1.0"`. Otherwise, the others have no version specified and default to `VERSION="0.1"` as specified in the Transformers base class in `transformers.py`
=> Static versioning for transformers

pliers/datasets/dictionaries.json, pliers/extractors/api.py, pliers/tests/test_datasets.py
The extractor was accidentally setting the `ExtractorResult` duration to `stim.onset` instead of `stim.duration`.
The Text and Image subclasses of `IndicoAPIExtractor` need to have dependency verification before trying to access the `allowed_models`.
=> Quick fixes in Indico extractors

pliers/tests/test_transformers.py
In pytest 3.3.0 `capsys` was updated.
Need to catch sys err within `pytest.raises` to inspect it.
=> Fix catching syserr

pliers/extractors/api.py
If you wouldn't be opposed, I think it would be handy to log the names of the models that were requested from the API. Otherwise, its hidden in each API's idiosyncratic python object, and it's a bit cumbersome to dig out.
=> Log model names

pliers/__init__.py, setup.py
currently, if installing into environment without `six`, importing `__version__` within `setup.py` leads to a chain of imports that break installation.
This PR avoids this import and parses the variables within `version.py` directly, as well as allows easier version checking
```
python -c "import pliers; print(pliers.__version__)"
```
=> fix: bare installation

pliers/stimuli/base.py
#236 
For DataLad AutoMagicIO to work with unavailable remote files in `load_stims`
Changes `exists` to `isfile` (to trigger download) and then uses `realpath` (which is probably a good thing to do anyways). 
Note, `isfile` must be called on symlink, which is file why I only use `realpath` in `load_file` not earlier. 
Another gotcha is that AutoMagicIO must be activated before `load_stims` is imported.
=> Use isfile and realpath in load_stims to integrate with DataLad

optional-dependencies.txt, pliers/__init__.py, pliers/external/pysaliency/__init__.py, pliers/extractors/image.py, pliers/support/due.py
- I have placed reference for the article into "pliers" code while citation for the module itself into your copy of the pySilencyMap
- here is currently "used" tags we defined in duecredit: https://github.com/duecredit/duecredit/#tags  If you see how we could improve, please suggest ;)
Demo (including the failing test):
```shell
$> DUECREDIT_ENABLE=1 python -m pytest -s -v pliers/tests/extractors/test_image_extractors.py::test_saliency_extractor
================================================================= test session starts ==================================================================
platform linux2 -- Python 2.7.14+, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /home/yoh/proj/misc/pliers/venvs/dev/bin/python
cachedir: .cache
rootdir: /home/yoh/proj/misc/pliers, inifile:
plugins: …
```
=> ENH: Initial support for duecredit

pliers/extractors/base.py, pliers/graph.py, pliers/stimuli/base.py, pliers/tests/test_graph.py, pliers/transformers/base.py
Improvements to the Graph API including:
- Allowing graphs to return stims (when calling `.run` with `merge=False`), which is useful for creating `Graph`s for preprocessing pipelines composed of only `Filter`s and `Converter`s
- `to_json` and `save` methods for graph objects for simple serialization and loading
- Ability to add linear chains (sequence of transformers) to a `Graph` using the `add_nodes` method with `mode='vertical'` or the `add_chain` method
- Style updates to the `draw` method, including representing implicit transformations with dotted borders and color coding stimuli and transformers
- The latter is still a WIP as the color coding needs work aesthetically
Resolves #249
Resolves #225
Resolves #224
=> Graph improvements

pliers/transformers/api/google.py
To prevent hitting usage quotas, until we can figure out a best default.
@adelavega 
@tyarkoni
=> Setting Google default batch size to 1

pliers/tests/test_updater.py, pliers/transformers/base.py, pliers/utils/updater.py
Updater was failing due to a change in the structure of `ExtractorResult` and differences between Convertors and Extractors.
In addition, only the first result may have been checked in extractors, so now I'm hashing all results including those from Extractors
=> Fix support for converters to updater

pliers/extractors/base.py, pliers/tests/extractors/test_extractors.py, pliers/tests/utils.py
Addresses #274 
Waiting on tests. 
Started by only appending `_` to `order`, `duration` and `onset`
Question is if this change should only affect `to_df` or if similar changes should be made throughout pliers. If individual extractors implement `to_df`, do they also need to be changed?
I'm also guessing there will be a lot of downstream effects of changing these column names.
=> Append _ to protected names in to_df

pliers/extractors/api/clarifai.py, pliers/extractors/api/indico.py, pliers/extractors/text.py, pliers/tests/extractors/api/test_clarifai_extractors.py, pliers/tests/extractors/api/test_google_extractors.py, pliers/tests/extractors/api/test_indico_extractors.py, pliers/tests/test_transformers.py, pliers/transformers/api/google.py, pliers/transformers/base.py
Implementation of caching in `BatchTransformerMixin`. This required custom code in `pliers/transformers/base.py` in the `_iterate` method that kept track of repeated elements in a batch or elements already in the cache. 
Also added to some docstrings and the `batch_size` argument everywhere explicitly.
Resolves #272
=> Batch caching

pliers/stimuli/base.py, pliers/stimuli/image.py, pliers/stimuli/text.py, pliers/tests/extractors/api/test_google_extractors.py, pliers/tests/test_stims.py
Addresses #293 by adding a `_hash_contents` property. So far only have overriden this in `ComplexTextStim` to be the text of all the elements joined.  
Test added to cover original issue with `ComplextTextExtractor`
Also fixes test for `GooglePropertyExtractor`
=> Unique hashing + test fix

.travis.yml, pliers/converters/api/google.py, pliers/filters/text.py, pliers/filters/video.py, pliers/stimuli/audio.py, pliers/stimuli/text.py, pliers/stimuli/video.py, pliers/tests/extractors/api/test_google_extractors.py, pliers/tests/extractors/test_image_extractors.py, pliers/tests/filters/test_video_filters.py, pliers/tests/test_graph.py, pliers/tests/test_stims.py, pliers/transformers/api/google.py
A couple patches to the mechanics of `VideoStim` and `VideoFrameCollectionStim`.
-Changed the `get_frame` method to only accept an `onset` argument on `VideoStim`s, since this becomes ambiguous for `VideoFrameCollectionStim`s anyways
-Updates to make the sampling more accurate (rounded at the appropriate moment) in the `FrameSamplingFilter`. Made it possible to perform upsampling, but took away the ability to sample on an already-sampled `VideoFrameCollectionStim`
Resolves #294
Resolves #298
Cherry picked some commits from #299.
-Resolves #290. Removes punctuation that count as tokens
-Small update to the `speech_contexts` argument for the `GoogleSpeechAPIConverter`
-Small fix for audio sampling rate if initialized from an existing clip
-Added functionality to `ComplexTextStim` to enable …
=> Various bug fixes and minor cleanups

.travis.yml, pliers/stimuli/audio.py, requirements.txt
In light of moviepy being released with our patch (https://github.com/Zulko/moviepy/pull/665), we can go ahead and remove this bit of code to hack AudioStim sampling rate.
Requires users to install the newest version of moviepy.
Librosa on 2.7 still failing, not sure what's taking the new release so long.
=> Removed old code in AudioStim

pliers/converters/api/google.py
In using the GoogleSpeechAPIConverter within pliers I noticed a mistake in the location where the list containing all the transcribed words is assigned. The list is re-assigned with every new response from the API and so whatever was in all of the previous responses would get overwritten and only the last speech block will be returned as the final output.
I just quickly moved it outside the for loop so if it's transcribing a clip with multiple audio blocks, everything would get returned.
=> Changed location of words list assignment for GoogleSpeechAPIConverter

.gitignore, optional-dependencies.txt, pliers/converters/__init__.py, pliers/converters/api/__init__.py, pliers/converters/api/google.py, pliers/converters/api/ibm.py, pliers/converters/api/revai.py, pliers/extractors/text.py, pliers/tests/converters/api/test_revai_converters.py, pliers/tests/extractors/test_audio_extractors.py, pliers/tests/extractors/test_text_extractors.py
Shameless self-promotion 😄
The Rev AI API should be more accurate and cheaper than the other APIs currently implemented in pliers (maybe only comparable with the Google "video" model for speech-to-text, which is more expensive). Already on our small obama_speech.wav test file, the transcript is essentially perfect. It should be particularly better for long-form audios such as podcasts, interviews, speeches, etc. One downside is the relatively slow turn-around time for short audios (in contrast to the relatively fast TAT for long audio).
Also in the PR:
-Miscellaneous linting updates
-Small bug fix for AudioToTextConverters where origin audio stim onset was being added twice
~Note: I added my trial credentials to travis, but these will expire after 300 free minutes~
Update: nevermind, …
=> Rev.ai speech-to-text API converter

.dockerignore, docker/Dockerfile, docker/README.md
I tried building a pliers docker image with the current Dockerfile, but it raised an error during the build. So I decided to refactor the image. This introduces some major changes into the image, but I think it streamlines it nicely. The docker image in this PR bootstraps `python:3.6-slim` and installs all dependencies from pip.
This image also adds a non-root user, so you can use jupyter without having to pass in `--allow-root`, and things are a bit safer in general.
=> ENH: dockerfile

pliers/filters/__init__.py, pliers/filters/image.py, pliers/tests/filters/test_image_filters.py
This PR proposes adding an image resizing filter, which can optionally maintain aspect ratio. This is following up https://github.com/tyarkoni/pliers/pull/341#discussion_r279959595.
Here is some test code:
```python
import os
from pliers.filters import ImageResizingFilter
from pliers.stimuli import ImageStim
from pliers.tests.utils import get_test_data_path
image_path = os.path.join(get_test_data_path(), 'image', 'apple.jpg')
from PIL import Image
image = ImageStim(filename=image_path)
resizer = ImageResizingFilter((299, 299), maintain_aspect_ratio=False)
new_stim = resizer.transform(image)
print(new_stim.data.shape)
Image.fromarray(new_stim.data)
resizer = ImageResizingFilter((299, 299), maintain_aspect_ratio=True)
new_stim = resizer.transform(image)
print(new_stim.data.shape) …
```
=> Add: ImageResizeFilter

docker/Dockerfile
This is to facilitate reuse of the docker image when fetched by singularity
on a system with an elderly kernel built without support of overlays and thus
requiring those directories (present on our HPC) to be present within image
No hurt feelings if rejected -- just wanted to check for an easy way out for myself ;)
=> ENH: precreate non standard /data /backup directories in Dockerfile

pliers/extractors/__init__.py, pliers/extractors/models.py, pliers/tests/extractors/test_image_extractors.py
This class accepts a model architecture string, and will use that pre-trained model from `tensorflow.keras.applications`. These changes also check whether `tensorflow.keras` is available. For image resizing, `pliers.filters.ImageResizingFilter` is used. The architecture 'inceptionv3' is the default.
Here is code for testing:
```python
import os
from pliers.extractors import TensorFlowKerasApplicationExtractor
from pliers.stimuli import ImageStim
from pliers.tests.utils import get_test_data_path
path = os.path.join(get_test_data_path(), 'image', 'apple.jpg')
image = ImageStim(path)
ext = TensorFlowKerasApplicationExtractor(architecture='inceptionv3')
result = ext.transform(image)
```
=> ENH: replace tensorflow extractor with more generic version.

docker/Dockerfile
the first call `python -m pliers.support.download` is done within source code tree, so mileage could vary from calling from outside
=> ENH: Dockerfile - chmod to guarantee availability, and test global installation via import pliers

pliers/extractors/api/clarifai.py, pliers/tests/extractors/api/test_clarifai_extractors.py
Toying around with the face detection models of clarifai, I noticed that while the extraction works, the transformation into a dataframe with ``_to_df()`` fails due to KeyErrors.
This is a very basic safe guard that checks whether the model used for the clarifai client is a Face Detection model (they identify it by this character string) and if so, returns the face region boundaries as a dataframe if a face is present and nothing if no face is present.
I had plenty of problems testing all if this locally, because I exceeded my free request limit, so I'm PRing a work in progress for further discussion about alternatives, or any other improvements.
=> [WIP] safeguard against keyerror in clarifai face detection

docs/installation.rst, setup.py
This adds and `extras_require` field to the `setup.py`, which should all users to optionally install all optional dependencies using `pip install pliers[all]`. This duplicates the functionality of `pip install -r optional-dependencies.txt`, but without installing from GitHub. The installation runs, but I haven't fully verified that everything works perfectly because I'm currently running into a `dlib` installation error for other reasons. I also made a small update to the installation documentation to reflect this change.
=> Added optional dependences as 'extras' for pip install

pliers/extractors/api/clarifai.py, pliers/tests/extractors/api/test_clarifai_extractors.py
My previous PR (#355) adjusted the clarifai face detection model to work only with single face images. In the case of more than one image, only the last image would be returned. This PR returns all detected faces in an image or video in a multi-row data frame.
I've also added basic tests that check whether more than a single face is returned in the case of multiple faces in the stimuli.
Copying the google API face extraction, I've added a parameter to return only the first face, if desired (`handle_annotations'), but I'm not using that anywhere so far (mainly because I can't find it used for Google anywhere).
=> [WIP] Adjust clarifai face detection model for multi-face stimuli

pliers/extractors/api/google.py
Closes #359 
Not sure why this new syntax is required (the API should be v1, and according to documentation, it should still operate the same)
=> Patch operations request for Google Video Intelligence

.travis.yml
Trying to fix random miniconda failures, inspired by: https://github.com/theochem/cgrid/blob/03a995a602fe043ee9c05e3797ffaa9836fa031f/.travis.yml
=> Try conditional caching of miniconda

.travis.yml
Fixes timing out travis tests by splitting up the py.test calls into four.
=> Split pytest into multiple calls to avoid memory limits

.travis.yml, pliers/tests/conftest.py
- Try to make the outputs of Travis as readable as possible (clean up clutter)
=> Limit pytest outputs for readability

.travis.yml, optional-dependencies.txt, pliers/extractors/__init__.py, pliers/extractors/audio.py, pliers/extractors/base.py, pliers/filters/audio.py, pliers/support/__init__.py, pliers/support/exceptions.py, pliers/support/setup_yamnet.py, pliers/tests/extractors/test_audio_extractors.py
wrapper for https://github.com/tensorflow/models/blob/master/research/audioset/yamnet/yamnet.py extracting label probability for 521 audio events from AudioSet hierarchical ontology.
=> yamnet architecture for audioset label extractor

pliers/extractors/base.py
A small bug in the `to_df `function which was causing incorrect `df` for some Extractors (`Clarifai` in this instance).
Only applies to those Extractors with no `_to_df` function and outputs in long format. 
I accidentally made all the columns index_cols include the feature names itself for that case.
=> Fix index cols for no _to_df

pliers/converters/__init__.py, pliers/converters/base.py, pliers/converters/misc.py, pliers/extractors/base.py, pliers/stimuli/__init__.py, pliers/stimuli/base.py, pliers/stimuli/misc.py, pliers/tests/converters/test_converters.py, pliers/tests/test_stims.py
This PR adds an `ExtractorResultToSeriesConverter` class that converts an `ExtractorResult` instance into a list of `SeriesStim` instances. The `SeriesStim` is also new, and is just a wrapper around a pandas `Series`. This allows us to build extractors that operate on the outputs of other extractors (e.g., to compute summary statistics over multiple columns). It's a bit inelegant in that it required a bit (but only a bit) of *sui generis* handling of `ExtractorResult` inputs (since we can otherwise assume `Transformer` inputs are always `Stim` subclasses), but I think it's a small price to pay for the added flexibility.
@rbroc, in principle, the existing automatic conversion detection should kick in without having to do anything further, so any `Extractor` that specifies a `SeriesStim` …
=> Add ExtractorResult --> SeriesStim converter

pliers/extractors/audio.py
Fixing a bug that caused mismatch between labels and values when passing subset of AudioSet labels to AudioSet extractor.
=> fix labels indexing issue in Audioset extractor

pliers/extractors/api/google.py
This should fix the issue with Google Face extractor. It seems sometimes it returned landmark annotations without a type. I just chose to skip them.
=> FIX: If Google Face Extractor result landmark has no type, skip. 

docker/Dockerfile
This commit reduces the uncompressed image size by about 1 GB. A major change is that a python virtual environment is used within the Docker image. This is done so that all installed dependencies are below one directory, and this directory can be copied into the final build stage.
I built an image using this branch available at https://hub.docker.com/r/kaczmarj/pliers (`docker pull kaczmarj/pliers`).
I was inspired to update the dockerfile after the discussion in #347
=> ENH: use multi-stage builds in Dockerfile to reduce final image size

pliers/extractors/misc.py
Minor removal of vestigial Python 2 super call.
Fixes #371 
The rest was taken care of in a recent PR #392
=> Remove instance of Python2 super

README.md
The links to the docs 404 and I couldn't find them for a bit. The other links seem to forward to the correct places though
=> update readme to link to correct pliers docs page

docker/Dockerfile
=> [FIX] remove --no-user-group

pliers/tests/test_graph.py
looks like one of the changes in #418 [had a regression with the Google API](https://travis-ci.com/github/PsychoinformaticsLab/pliers/jobs/387471662#L1294),
This pull request aims to fix the regression.
=> [FIX] access string in numpy array

pliers/tests/extractors/api/test_google_extractors.py, pliers/tests/test_transformers.py
=> Fix Google Api regressions - 2

pliers/extractors/base.py, pliers/tests/test_utils.py, pliers/utils/__init__.py, pliers/utils/base.py
I took a stab at implementing #426 , mostly copying over the logic from pybids.
I decided to combine the upsample and resample logic, although I could see the argument against (although I also find it hard to "detect" the current sampling rate, so it seems easier to simply upsample it). 
Still need to:
- Do the operation in place (e.g. replace the data in the `ExtractedFeature` object)
- Consider `object_id` and other cases that could screw this logic up
- Add to `Graph`
I think otherwise it's fairly close to the logic being implemented by pybids, however, something about the results seem a bit funny to me.
Take this example:
```
from pliers.extractors import RMSExtractor 
from pliers.tests.utils import get_test_data_path   
ext = RMSExtractor()
res = ext.transform(get_test_data_path() + …
```
=> Resample ExtractedFeatures

pliers/extractors/text.py, pliers/tests/extractors/test_text_extractors.py
Recent versions of huggingface's `transformers` return model outputs as a `ModelOutput` objects.
All BERT extractors have been adapted accordingly.
=> update huggingface BERT extractors

pliers/diagnostics/diagnostics.py, pliers/tests/test_utils.py, pliers/utils/scikit.py, requirements.txt
Closes #437
Calls to deprecated `ix`, `nonzero` and `as_matrix` have been replaced by supported methods (`iloc`, `to_numpy`), tests are now passing (and hey, GitHub actions is great!)
@tyarkoni @adelavega - I've set `pandas>=0.24` in the requirements file. Done some local testing, and that seems to be the earliest version supporting the new methods. But we could also be more conservative and set to `>=1.0` -  any thoughts on that?
Other than that should be ready to merge.
=> remove deprecated pandas methods

pliers/tests/extractors/test_misc_extractors.py, pliers/tests/test_io.py, pliers/tests/test_stims.py
Closes https://github.com/PsychoinformaticsLab/pliers/issues/440
Replacing `BertLMExtractor` with `VADERSentimentExtractor`.
=> replace BERT with lighter extractor in metric extractor tests

README.rst, docs/requirements.txt, setup.py
Adds @adelavega's excellent video explaining pliers at the **TOP**, since people like watching things more than reading, and link corresponding tutorial/course in readme.
=> [DOC] Add video

.gitignore, optional-dependencies.txt, pliers/converters/api/revai.py, pliers/tests/converters/api/test_revai_converters.py
Closes #479.
- Adds a new `language` parameter to `RevAISpeechAPIConverter`, taking str values documented in the [API docs](https://docs.rev.ai/api/asynchronous/reference/#operation/SubmitTranscriptionJob!ct=application/json&path=language&t=request).
- Sets a minimum version of the `rev_ai` python SDK
- Implements a smoke test that non-supported languages error on conversion.
=> [enh] support non-English transcript with RevAI

pliers/extractors/__init__.py, pliers/extractors/models.py, pliers/tests/extractors/test_model_extractors.py
- Adds `TFHubAudioExtractor`
This extractor is very similar to `TFHubImageExtractor` but with 1) slightly different preprocessing 2) infers timing output of model (i.e. onsets, durations) from the output (assumes fixed sampling rate)
- Adds `saved_model` loading to `TFHubExtractor`. Models like `SPICE` are not meant to instantiated as `KerasLayer`. Instead, they must be loaded with `hub.load` and have predefined `signature` where the model is stores, and named vectors as outputs. 
For reference this is the `SPICE` model: https://tfhub.dev/google/spice/
=> Add TFHubAudioExtractor + SPICE Tests
